# Generated by Django 4.2.3 on 2023-07-31 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTienda', '0002_remove_producto_tiendaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tiendaProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionTienda.tienda'),
        ),
    ]
