# Generated by Django 4.2.3 on 2023-08-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTienda', '0004_alter_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
